/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.student.project;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {

    }
}
