/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.student.project;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class App extends Application{


    @Override
    public void start(Stage primaryStage) throws Exception {

    }
}
